### ISSUE TITLE
Tune S2 Width

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#81]
Suggested by @skazama to remove potential wall leakage events as in [this plot](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Akazama%3Aanomalous_bg_sr1&media=xenon:kazama:s2_width_vs_s2_er_leakage.png).

@zhut19 mentioned the cut may be already too tight, however looking at Figs. A12 and A13 in @weiyuehuan's [tuning note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:yuehuan:analysis:1sciencerun_s2width#appendix_3bug_of_this_cut_in_laxlichenssr1), seems like the previous straight line extrapolation can be tightened.

**Comment by pdeperio** [comment]
@zachgreene also reported some loss at high energy due to widening of the distribution apparent in [this figure](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenon1t%3Ayuehuan%3Aanalysis%3A1sciencerun_s2width&media=xenon:xenon1t:yuehuan:analysis:widthcut:bug:rn220_lax_zcut.png).

Also, in SR0, the MC-tuned straight lines by @JelleAalbers were chosen (instead of the fit by @weiyuehuan) since they had a higher MC-derived acceptance as shown [here](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenon1t%3Ayuehuan%3Aanalysis%3A0sciencerun_s2width_update0&media=xenon:xenon1t:yuehuan:analysis:widthcut:jelleaccp.png). However, there was no explicit data/MC comparison/validation of this, and looks like there may be some acceptance loss applying to data as shown [here](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenon1t%3Ayuehuan%3Aanalysis%3A1sciencerun_s2width&media=xenon:xenon1t:yuehuan:analysis:widthcut:bug:widthcut_corrected.png) and [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:chris:acceptancesr0), not accounted for in the analysis. We should reconsider the following:

1. Using the fit or straight lines,
2. Tuning on data or MC, and
3. Acceptance based on MC (if can validate data matching) or data (if can define a good control sample).

**Comment by zhut19** [comment]
If we take a look at simulated data we will see that we shouldn't tighten s2 width to remove those wall leakage events mentioned by @skazama  [link](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Akazama%3Aanomalous_bg_sr1&media=xenon:kazama:s2_width_vs_s2_er_leakage.png). Because, it will be effectively adding a S2 area threshold.

You can actually see that when S2 area get smaller, the s2 range 50p area over model has a big spread and most fall below 1 in this [sr0 tuning plot](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenon1t%3Ayuehuan%3Aanalysis%3A0sciencerun_s2width_update0&media=xenon:xenon1t:yuehuan:analysis:widthcut:jelledef.png).

To verify this, I use fax to generate s2 from 1 electron to 100 electrons and you can see in figure below, whose wall leakage events are well hid inside normal events.
<img width="935" alt="width_2" src="https://user-images.githubusercontent.com/16232525/31915208-9b58d240-b81b-11e7-8bf2-abc424cc0680.png">

**Comment by skazama** [comment]
thanks for fax simulation. Now I agree that we should not tighten the s2 width cut.
